# Generated by Django 6.0.7 on 2026-07-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
