# Generated by Django 6.0.7 on 2026-07-10 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detector', '0002_uploadedimage_original_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('prevention', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords that help detect this disease from filenames or labels.', max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='detector.category')),
            ],
            options={
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detector.category'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='predicted_disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detector.disease'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='prediction_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
