# Generated by Django 6.0.7 on 2026-07-10 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_seed_categories_and_diseases'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedimage',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
