# Generated by Django 6.0.7 on 2026-07-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0005_alter_uploadedimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='image_type',
            field=models.CharField(choices=[('plant', 'Plant'), ('human', 'Human'), ('animal', 'Animal'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='prediction_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='severity',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
